# 01 - Perfilado de calidad raw

**Objetivo.** Cargar los datasets crudos desde `data/raw` y documentar estructura, columnas, tipos de datos, nulos iniciales, valores inválidos que funcionan como faltantes, rangos, cardinalidad y duplicados.

Este notebook no modifica datos. Su salida sirve como evidencia de línea de base para justificar la limpieza posterior.

## Criterio de trabajo 

- Los archivos crudos se leen con rutas relativas al repositorio.
- Los crudos no se modifican.
- Airbnb se perfila desde `airbnb_caba_normalizado_mensual.csv`, porque ya es la base normalizada prioritaria para comparación.
- Los reportes se guardan en `data/processed/reports/`.

In [1]:
from pathlib import Path
import json
import re
import unicodedata
from datetime import datetime

import numpy as np
import pandas as pd

try:
    from IPython.display import display
except Exception:
    display = print

pd.set_option('display.max_columns', 140)
pd.set_option('display.max_rows', 100)
pd.set_option('display.width', 180)


def find_repo_root(start=None):
    start = Path(start or Path.cwd()).resolve()
    for path in [start, *start.parents]:
        if (path / 'data' / 'raw').exists() and (path / 'README.md').exists():
            return path
    raise FileNotFoundError('No se encontro la raiz del repo. Ejecutar dentro del proyecto.')

REPO_ROOT = find_repo_root()
RAW_DIR = REPO_ROOT / 'data' / 'raw'
PROCESSED_DIR = REPO_ROOT / 'data' / 'processed'
REPORTS_DIR = PROCESSED_DIR / 'reports'
EXTERNAL_DIR = REPO_ROOT / 'Fuentes_de_enriquecimiento'
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

print('REPO_ROOT:', REPO_ROOT)
print('RAW_DIR:', RAW_DIR)
print('PROCESSED_DIR:', PROCESSED_DIR)

REPO_ROOT: C:\Users\arira\OneDrive\Documents\GitHub\TP_analitica_descriptiva_grupo1_2q2026
RAW_DIR: C:\Users\arira\OneDrive\Documents\GitHub\TP_analitica_descriptiva_grupo1_2q2026\data\raw
PROCESSED_DIR: C:\Users\arira\OneDrive\Documents\GitHub\TP_analitica_descriptiva_grupo1_2q2026\data\processed

## Carga de archivos raw

In [2]:
#set de marcadores para identificar nulos, si se encuentran mas en el analisis se agregan aca y ejecuta la limpeza nuevamente
INVALID_MARKERS = { 
    '', ' ', 'nan', 'NaN', 'NAN', 'none', 'None', 'NONE', 'null', 'NULL',
    's/d', 'S/D', 'sd', 'SD', 'sin dato', 'Sin dato', 'Sin Datos', 'SIN_DATO','sin datos',
    'no informa', 'No informa', 'no informado', 'No informado', 'n/a', 'N/A',
    '-', '--', '---', '?', '99999', '-99999', '-9999', '9999'
}

RAW_SOURCES = {
    'df_raw_meli_alq': {
        'descripcion': 'Mercado Libre - alquiler permanente',
        'paths': sorted((RAW_DIR / 'mercadolibre_inmuebles_alquiler').glob('meli_alq_*.csv')),
    },
    'df_raw_meli_alq_temp': {
        'descripcion': 'Mercado Libre - alquiler temporario',
        'paths': sorted((RAW_DIR / 'mercadolibre_inmuebles_alquiler temporario').glob('meli_alq_temp_*.csv')),
    },
    'df_raw_meli_vtas': {
        'descripcion': 'Mercado Libre - venta',
        'paths': sorted((RAW_DIR / 'mercadolibre_inmuebles_ventas').glob('meli_vtas_*.csv')),
    },
    'df_raw_argenprop': {
        'descripcion': 'Argenprop - publicaciones extraidas',
        'paths': [RAW_DIR / 'argenprop' / 'propiedades_argenprop.csv'],
    },
    'df_raw_zonaprop': {
        'descripcion': 'Zonaprop - publicaciones extraidas',
        'paths': [RAW_DIR / 'zonaprop' / 'propiedades_zonaprop.csv'],
    },
    'df_raw_airbnb_norm': {
        'descripcion': 'Airbnb CABA normalizado mensual. Base prioritaria para analisis comparable',
        'paths': [RAW_DIR / 'airbnb' / 'airbnb_caba_normalizado_mensual.csv'],
    },
}


def read_csv_safely(path):
    return pd.read_csv(path, low_memory=False)


def load_many(paths, source_name):
    existing = [Path(p) for p in paths if Path(p).exists()]
    if not existing:
        print(f'ATENCION: no se encontraron archivos para {source_name}')
        return pd.DataFrame()
    frames = []
    for path in existing:
        df = read_csv_safely(path)
        df['_archivo_origen'] = str(path.relative_to(REPO_ROOT))
        frames.append(df)
    return pd.concat(frames, ignore_index=True, sort=False)

raw_dfs = {}
for df_name, spec in RAW_SOURCES.items():
    raw_dfs[df_name] = load_many(spec['paths'], df_name)
    globals()[df_name] = raw_dfs[df_name]
    print(f"{df_name}: {raw_dfs[df_name].shape} | {spec['descripcion']}")

df_raw_meli_alq: (11479, 61) | Mercado Libre - alquiler permanente
df_raw_meli_alq_temp: (6190, 61) | Mercado Libre - alquiler temporario
df_raw_meli_vtas: (44013, 61) | Mercado Libre - venta
df_raw_argenprop: (162, 96) | Argenprop - publicaciones extraidas
df_raw_zonaprop: (980, 96) | Zonaprop - publicaciones extraidas
df_raw_airbnb_norm: (9596, 61) | Airbnb CABA normalizado mensual. Base prioritaria para analisis comparable

## Funciones de perfilado

In [3]:
COLUMN_DESCRIPTIONS = { #objetivo de ahora es entender los df con sus columnas
    'item_id': 'Identificador de publicacion en Mercado Libre.',
    'property_id': 'Identificador de publicacion o propiedad segun fuente.',
    'fuente': 'Portal o fuente de origen del registro.',
    'url': 'URL de la publicacion.',
    'search_url': 'URL de busqueda desde la cual fue capturada la publicacion.',
    'pagina_origen': 'Pagina de resultados donde aparecio la publicacion.',
    'scraped_at_utc': 'Fecha y hora de extraccion en UTC.',
    'titulo': 'Titulo publicado del aviso.',
    'descripcion': 'Descripcion textual del aviso cuando esta disponible.',
    'tipo_propiedad': 'Tipo de inmueble declarado o inferido.',
    'tipo_operacion': 'Tipo de operacion: venta, alquiler o alquiler temporal.',
    'moneda': 'Moneda del precio publicado.',
    'precio': 'Precio numerico extraido de la publicacion.',
    'precio_texto': 'Precio en formato textual original.',
    'precio_m2_min': 'Precio por metro cuadrado minimo calculado por Mercado Libre cuando hay rangos.',
    'precio_m2_max': 'Precio por metro cuadrado maximo calculado por Mercado Libre cuando hay rangos.',
    'precio_m2_calculado': 'Precio por metro cuadrado calculado por scraper en Argenprop/Zonaprop.',
    'barrio': 'Barrio declarado, inferido o capturado desde la fuente.',
    'barrio_norm': 'Barrio normalizado para analisis territorial.',
    'comuna': 'Comuna de CABA cuando esta disponible o inferida.',
    'localidad': 'Localidad declarada.',
    'provincia': 'Provincia o jurisdiccion declarada.',
    'direccion': 'Direccion capturada en Mercado Libre.',
    'direccion_completa': 'Direccion capturada en Argenprop/Zonaprop/Airbnb.',
    'calle': 'Calle extraida o inferida.',
    'altura': 'Altura aproximada o declarada.',
    'latitud': 'Latitud de la publicacion cuando la fuente la informa.',
    'longitud': 'Longitud de la publicacion cuando la fuente la informa.',
    'ambientes_min': 'Minimo de ambientes informado cuando la publicacion usa rangos.',
    'ambientes_max': 'Maximo de ambientes informado cuando la publicacion usa rangos.',
    'ambientes': 'Cantidad de ambientes.',
    'dormitorios_min': 'Minimo de dormitorios informado cuando la publicacion usa rangos.',
    'dormitorios_max': 'Maximo de dormitorios informado cuando la publicacion usa rangos.',
    'dormitorios': 'Cantidad de dormitorios.',
    'banios_min': 'Minimo de banios informado cuando la publicacion usa rangos.',
    'banios_max': 'Maximo de banios informado cuando la publicacion usa rangos.',
    'banios': 'Cantidad de banios.',
    'superficie_min_m2': 'Superficie minima en m2 informada o inferida.',
    'superficie_max_m2': 'Superficie maxima en m2 informada o inferida.',
    'superficie_total_m2': 'Superficie total en m2.',
    'superficie_cubierta_m2': 'Superficie cubierta en m2.',
    'tipo_superficie': 'Tipo de superficie usada para el dato de m2.',
    'inmobiliaria': 'Nombre de inmobiliaria o anunciante cuando esta disponible.',
    'seller_id': 'Identificador del vendedor/anfitrion cuando existe.',
    'seller_nombre': 'Nombre del anfitrion/vendedor en Airbnb.',
    'seller_superhost': 'Indicador de superhost en Airbnb.',
    'rating': 'Puntaje promedio de la publicacion en Airbnb.',
    'reviews': 'Cantidad de resenias en Airbnb.',
    'cantidad_imagenes': 'Cantidad de imagenes detectadas.',
    'imagen_principal': 'URL de imagen principal.',
    'parse_warnings': 'Advertencias del proceso de parseo.',
    'parse_ok': 'Indicador de parseo exitoso.',
    'http_status': 'Codigo HTTP de respuesta durante scraping.',
    'apto_credito': 'Indicador de apto credito.',
    'balcon': 'Indicador de balcon.',
    'balcon_o_patio': 'Indicador de balcon o patio en Airbnb.',
    'terraza': 'Indicador de terraza.',
    'pileta': 'Indicador de pileta.',
    'parrilla': 'Indicador de parrilla.',
    'cochera_mencionada': 'Indicador de cochera mencionada en Mercado Libre.',
    'cochera': 'Indicador de cochera en Airbnb/otros portales.',
    'amenities_mencionadas': 'Indicador de amenities mencionadas en Mercado Libre.',
    'precio_sospechoso': 'Indicador de precio sospechoso en Airbnb normalizado.',
    'unidad_precio': 'Unidad de referencia del precio Airbnb.',
    'precio_regimen': 'Regimen de precio Airbnb: por noche, mensual, etc.',
}


def example_value(series):
    sample = series.dropna().head(1)
    if sample.empty:
        return np.nan
    text = str(sample.iloc[0])
    return text[:120] + ('...' if len(text) > 120 else '')


def column_dictionary(df, dataset_name):
    rows = []
    for col in df.columns:
        rows.append({
            'dataset': dataset_name,
            'columna': col,
            'tipo_dato': str(df[col].dtype),
            'descripcion': COLUMN_DESCRIPTIONS.get(col, 'Pendiente de documentar segun significado en la fuente.'),
            'ejemplo': example_value(df[col]),
        })
    return pd.DataFrame(rows)


def invalid_like_missing_count(series):
    if not (pd.api.types.is_object_dtype(series) or pd.api.types.is_string_dtype(series)):
        return 0
    normalized = series.astype('string').str.strip()
    return int(normalized.isin(INVALID_MARKERS).sum())


def usability_comment(null_pct, invalid_pct, n_labels, dtype):
    missing_pct = max(null_pct, invalid_pct)
    if missing_pct >= 80:
        return 'baja: faltantes muy altos; usar solo como referencia secundaria'
    if missing_pct >= 40:
        return 'media-baja: requiere justificacion antes de usar en KPIs'
    if missing_pct >= 15:
        return 'media: usable con controles y posible segmentacion'
    if n_labels > 300 and dtype == 'categorica':
        return 'media: alta cardinalidad; revisar si es identificador/texto libre'
    return 'alta: utilizable para analisis inicial'


def quality_profile(df, dataset_name):
    rows = []
    n = len(df)
    for col in df.columns:
        s = df[col]
        null_count = int(s.isna().sum())
        invalid_count = invalid_like_missing_count(s)
        is_num = pd.api.types.is_numeric_dtype(s)
        dtype_group = 'cuantitativa' if is_num else 'categorica/texto/fecha'
        numeric_min = s.min(skipna=True) if is_num and s.notna().any() else np.nan
        numeric_max = s.max(skipna=True) if is_num and s.notna().any() else np.nan
        n_labels = int(s.nunique(dropna=True)) if not is_num else np.nan
        null_pct = round(null_count / n * 100, 2) if n else np.nan
        invalid_pct = round(invalid_count / n * 100, 2) if n else np.nan
        rows.append({
            'dataset': dataset_name,
            'columna': col,
            'tipo_dato': str(s.dtype),
            'tipo_variable': dtype_group,
            'n_filas': n,
            'nulos_iniciales': null_count,
            'pct_nulos_iniciales': null_pct,
            'invalidos_tipo_faltante': invalid_count,
            'pct_invalidos_tipo_faltante': invalid_pct,
            'min_cuantitativa': numeric_min,
            'max_cuantitativa': numeric_max,
            'n_labels_categorica': n_labels,
            'comentario_usabilidad_calidad': usability_comment(null_pct, invalid_pct, 0 if pd.isna(n_labels) else n_labels, 'cuantitativa' if is_num else 'categorica'),
        })
    return pd.DataFrame(rows)


def dataset_inventory(dfs):
    rows = []
    for name, df in dfs.items():
        scraped_col = 'scraped_at_utc' if 'scraped_at_utc' in df.columns else None
        scraped_min = scraped_max = np.nan
        if scraped_col:
            dates = pd.to_datetime(df[scraped_col], errors='coerce', utc=True)
            if dates.notna().any():
                scraped_min = dates.min()
                scraped_max = dates.max()
        rows.append({
            'dataframe': name,
            'filas': len(df),
            'columnas': df.shape[1],
            'memoria_mb': round(df.memory_usage(deep=True).sum() / 1024**2, 2),
            'fecha_extraccion_min': scraped_min,
            'fecha_extraccion_max': scraped_max,
            'archivos_origen': df['_archivo_origen'].nunique() if '_archivo_origen' in df.columns else np.nan,
        })
    return pd.DataFrame(rows)

## Inventario general de datasets

In [4]:
inventario_raw = dataset_inventory(raw_dfs)
display(inventario_raw) #resumen de conformado de datasets y extracciones
inventario_raw.to_csv(REPORTS_DIR / 'inventario_raw.csv', index=False)

              dataframe  filas  columnas  memoria_mb             fecha_extraccion_min             fecha_extraccion_max  archivos_origen
0       df_raw_meli_alq  11479        61       26.90 2026-09-03 16:45:14.494669+00:00 2026-09-05 20:06:33.128720+00:00                2
1  df_raw_meli_alq_temp   6190        61       15.01 2026-09-03 17:22:27.502870+00:00 2026-09-05 20:52:13.036557+00:00                2
2      df_raw_meli_vtas  44013        61      103.65 2026-08-15 15:28:55.553461+00:00 2026-09-03 16:42:08.328566+00:00                2
3      df_raw_argenprop    162        96        0.63 2026-08-15 23:56:14.395650+00:00 2026-09-03 15:09:36.365547+00:00                1
4       df_raw_zonaprop    980        96        5.76 2026-08-17 20:48:48.072806+00:00 2026-09-03 15:12:53.379325+00:00                1
5    df_raw_airbnb_norm   9596        61       33.83        2026-09-05 16:19:29+00:00        2026-09-06 05:39:56+00:00                1

## Diccionario inicial de columnas

Tabla con columna, tipo de dato, descripción inicial y ejemplo, a referenciar siempre que se necesite entender una columna. Las descripciones pendientes deben completarse si la variable se vuelve central para el análisis.

In [5]:
diccionario_raw_inicial = pd.concat([column_dictionary(df, name) for name, df in raw_dfs.items()], ignore_index=True)
display(diccionario_raw_inicial.head(100))
diccionario_raw_inicial.to_csv(PROCESSED_DIR / 'diccionario_raw_inicial.csv', index=False)

                 dataset                 columna tipo_dato                                        descripcion                                            ejemplo
0        df_raw_meli_alq                 item_id       str     Identificador de publicacion en Mercado Libre.                                      MLA2052442697
1        df_raw_meli_alq                  fuente       str            Portal o fuente de origen del registro.                                      Mercado Libre
2        df_raw_meli_alq                     url       str                             URL de la publicacion.  https://departamento.mercadolibre.com.ar/MLA-2...
3        df_raw_meli_alq              search_url       str  URL de busqueda desde la cual fue capturada la...  https://inmuebles.mercadolibre.com.ar/departam...
4        df_raw_meli_alq           pagina_origen     int64  Pagina de resultados donde aparecio la publica...                                                  1
5        df_raw_meli_alq          scraped_at_utc       str                 Fecha y hora de extraccion en UTC.                   2026-09-03T16:45:14.494669+00:00
6        df_raw_meli_alq                  titulo       str                        Titulo publicado del aviso.  Departamento En Alquiler De 4 Ambientes Con De...
7        df_raw_meli_alq          tipo_propiedad       str             Tipo de inmueble declarado o inferido.                                       departamento
8        df_raw_meli_alq          tipo_operacion       str  Tipo de operacion: venta, alquiler o alquiler ...                                           alquiler
9        df_raw_meli_alq                  moneda       str                       Moneda del precio publicado.                                                USD
10       df_raw_meli_alq                  precio   float64        Precio numerico extraido de la publicacion.                                             5000.0
11       df_raw_meli_alq            precio_texto       str                Precio en formato textual original.                                          US$ 5.000
12       df_raw_meli_alq                   desde     int64  Pendiente de documentar segun significado en l...                                                  0
13       df_raw_meli_alq            inmobiliaria       str  Nombre de inmobiliaria o anunciante cuando est...                                Khabbaz Propiedades
14       df_raw_meli_alq               direccion       str              Direccion capturada en Mercado Libre.      Segui Al 3600, Palermo Chico, Capital Federal
15       df_raw_meli_alq                  barrio       str  Barrio declarado, inferido o capturado desde l...                                      Palermo Chico
16       df_raw_meli_alq               localidad       str                               Localidad declarada.                                    Capital Federal
17       df_raw_meli_alq               provincia       str                Provincia o jurisdiccion declarada.                                    Capital Federal
18       df_raw_meli_alq           ambientes_min   float64  Minimo de ambientes informado cuando la public...                                                4.0
19       df_raw_meli_alq           ambientes_max   float64  Maximo de ambientes informado cuando la public...                                                4.0
20       df_raw_meli_alq              banios_min   float64  Minimo de banios informado cuando la publicaci...                                                3.0
21       df_raw_meli_alq              banios_max   float64  Maximo de banios informado cuando la publicaci...                                                3.0
22       df_raw_meli_alq         dormitorios_min   float64  Minimo de dormitorios informado cuando la publ...                                                1.0
23       df_raw_meli_alq         dormitorios_max   float64  Maximo de dormitorios informado cuando la publ...                                                1.0
24       df_raw_meli_alq       superficie_min_m2   float64      Superficie minima en m2 informada o inferida.                                              210.0
25       df_raw_meli_alq       superficie_max_m2   float64      Superficie maxima en m2 informada o inferida.                                              210.0
26       df_raw_meli_alq         tipo_superficie       str       Tipo de superficie usada para el dato de m2.                                              total
27       df_raw_meli_alq        imagen_principal       str                           URL de imagen principal.  https://http2.mlstatic.com/D_NQ_NP_2X_926918-M...
28       df_raw_meli_alq               destacado     int64  Pendiente de documentar segun significado en l...                                                  1
29       df_raw_meli_alq          emprendimiento     int64  Pendiente de documentar segun significado en l...                                                  0
30       df_raw_meli_alq                posesion   float64  Pendiente de documentar segun significado en l...                                                NaN
31       df_raw_meli_alq    unidades_disponibles   float64  Pendiente de documentar segun significado en l...                                                NaN
32       df_raw_meli_alq         atributos_texto       str  Pendiente de documentar segun significado en l...                 4 ambs. | 3 baños | 210 m² totales
33       df_raw_meli_alq           texto_tarjeta       str  Pendiente de documentar segun significado en l...  PUBLICADO ESTA SEMANA Departamento en alquiler...
34       df_raw_meli_alq          parse_warnings   float64                Advertencias del proceso de parseo.                                                NaN
35       df_raw_meli_alq         posicion_pagina     int64  Pendiente de documentar segun significado en l...                                                  1
36       df_raw_meli_alq                    slug       str  Pendiente de documentar segun significado en l...  MLA-2052442697-departamento-en-alquiler-de-4-a...
37       df_raw_meli_alq                   calle       str                         Calle extraida o inferida.                                           Segui Al
38       df_raw_meli_alq                  altura   float64                     Altura aproximada o declarada.                                             3600.0
39       df_raw_meli_alq                  comuna   float64  Comuna de CABA cuando esta disponible o inferida.                                               14.0
40       df_raw_meli_alq         precio_anterior   float64  Pendiente de documentar segun significado en l...                                             1957.0
41       df_raw_meli_alq           descuento_pct   float64  Pendiente de documentar segun significado en l...                                           -33114.1
42       df_raw_meli_alq           precio_m2_min   float64  Precio por metro cuadrado minimo calculado por...                                              23.81
43       df_raw_meli_alq           precio_m2_max   float64  Precio por metro cuadrado maximo calculado por...                                              23.81
44       df_raw_meli_alq  amplitud_superficie_m2   float64  Pendiente de documentar segun significado en l...                                                0.0
45       df_raw_meli_alq     es_rango_superficie   float64  Pendiente de documentar segun significado en l...                                                0.0
46       df_raw_meli_alq      es_rango_ambientes   float64  Pendiente de documentar segun significado en l...                                                0.0
47       df_raw_meli_alq            monoambiente     int64  Pendiente de documentar segun significado en l...                                                  0
48       df_raw_meli_alq            apto_credito     int64                         Indicador de apto credito.                                                  0
49       df_raw_meli_alq                  balcon     int64                               Indicador de balcon.                                                  0
50       df_raw_meli_alq                 terraza     int64                              Indicador de terraza.                                                  0
51       df_raw_meli_alq                  pileta     int64                               Indicador de pileta.                                                  0
52       df_raw_meli_alq                parrilla     int64                             Indicador de parrilla.                                                  0
53       df_raw_meli_alq      cochera_mencionada     int64  Indicador de cochera mencionada en Mercado Libre.                                                  1
54       df_raw_meli_alq   amenities_mencionadas     int64  Indicador de amenities mencionadas en Mercado ...                                                  1
55       df_raw_meli_alq          estado_entrega    object  Pendiente de documentar segun significado en l...                                  entrega_inmediata
56       df_raw_meli_alq      cantidad_atributos     int64  Pendiente de documentar segun significado en l...                                                  3
57       df_raw_meli_alq         completitud_pct   float64  Pendiente de documentar segun significado en l...                                              100.0
58       df_raw_meli_alq               imagen_id       str  Pendiente de documentar segun significado en l...         D_NQ_NP_2X_926918-MLA116997522333_082026-E
59       df_raw_meli_alq        imagen_extension       str  Pendiente de documentar segun significado en l...                                               webp
60       df_raw_meli_alq         _archivo_origen       str  Pendiente de documentar segun significado en l...  data\raw\mercadolibre_inmuebles_alquiler\meli_...
61  df_raw_meli_alq_temp                 item_id       str     Identificador de publicacion en Mercado Libre.                                      MLA2698335478
62  df_raw_meli_alq_temp                  fuente       str            Portal o fuente de origen del registro.                                      Mercado Libre
63  df_raw_meli_alq_temp                     url       str                             URL de la publicacion.  https://departamento.mercadolibre.com.ar/MLA-2...
64  df_raw_meli_alq_temp              search_url       str  URL de busqueda desde la cual fue capturada la...  https://inmuebles.mercadolibre.com.ar/departam...
65  df_raw_meli_alq_temp           pagina_origen     int64  Pagina de resultados donde aparecio la publica...                                                  1
66  df_raw_meli_alq_temp          scraped_at_utc       str                 Fecha y hora de extraccion en UTC.                   2026-09-03T17:22:27.502870+00:00
67  df_raw_meli_alq_temp                  titulo       str                        Titulo publicado del aviso.  Departamento Alquiler Temporario 3 Ambientes A...
68  df_raw_meli_alq_temp          tipo_propiedad       str             Tipo de inmueble declarado o inferido.                                       departamento
69  df_raw_meli_alq_temp          tipo_operacion       str  Tipo de operacion: venta, alquiler o alquiler ...                                  alquiler temporal
70  df_raw_meli_alq_temp                  moneda       str                       Moneda del precio publicado.                                                USD
71  df_raw_meli_alq_temp                  precio   float64        Precio numerico extraido de la publicacion.                                             1400.0
72  df_raw_meli_alq_temp            precio_texto       str                Precio en formato textual original.                                          US$ 1.400
73  df_raw_meli_alq_temp                   desde     int64  Pendiente de documentar segun significado en l...                                                  0
74  df_raw_meli_alq_temp            inmobiliaria       str  Nombre de inmobiliaria o anunciante cuando est...                            Alternativa Propiedades
75  df_raw_meli_alq_temp               direccion       str              Direccion capturada en Mercado Libre.     Av. Cnel. Díaz 2400, Recoleta, Capital Federal
76  df_raw_meli_alq_temp                  barrio       str  Barrio declarado, inferido o capturado desde l...                                           Recoleta
77  df_raw_meli_alq_temp               localidad       str                               Localidad declarada.                                    Capital Federal
78  df_raw_meli_alq_temp               provincia       str                Provincia o jurisdiccion declarada.                                    Capital Federal
79  df_raw_meli_alq_temp           ambientes_min   float64  Minimo de ambientes informado cuando la public...                                                3.0
80  df_raw_meli_alq_temp           ambientes_max   float64  Maximo de ambientes informado cuando la public...                                                3.0
81  df_raw_meli_alq_temp              banios_min   float64  Minimo de banios informado cuando la publicaci...                                                3.0
82  df_raw_meli_alq_temp              banios_max   float64  Maximo de banios informado cuando la publicaci...                                                3.0
83  df_raw_meli_alq_temp         dormitorios_min   float64  Minimo de dormitorios informado cuando la publ...                                                2.0
84  df_raw_meli_alq_temp         dormitorios_max   float64  Maximo de dormitorios informado cuando la publ...                                                2.0
85  df_raw_meli_alq_temp       superficie_min_m2   float64      Superficie minima en m2 informada o inferida.                                              120.0
86  df_raw_meli_alq_temp       superficie_max_m2   float64      Superficie maxima en m2 informada o inferida.                                              120.0
87  df_raw_meli_alq_temp         tipo_superficie       str       Tipo de superficie usada para el dato de m2.                                           cubierta
88  df_raw_meli_alq_temp        imagen_principal       str                           URL de imagen principal.  https://http2.mlstatic.com/D_NQ_NP_2X_786192-M...
89  df_raw_meli_alq_temp               destacado     int64  Pendiente de documentar segun significado en l...                                                  1
90  df_raw_meli_alq_temp          emprendimiento     int64  Pendiente de documentar segun significado en l...                                                  0
91  df_raw_meli_alq_temp                posesion    object  Pendiente de documentar segun significado en l...                                           Preventa
92  df_raw_meli_alq_temp    unidades_disponibles   float64  Pendiente de documentar segun significado en l...                                                4.0
93  df_raw_meli_alq_temp         atributos_texto       str  Pendiente de documentar segun significado en l...               3 ambs. | 3 baños | 120 m² cubiertos
94  df_raw_meli_alq_temp           texto_tarjeta       str  Pendiente de documentar segun significado en l...  Departamento en alquiler temporal Departamento...
95  df_raw_meli_alq_temp          parse_warnings   float64                Advertencias del proceso de parseo.                                                NaN
96  df_raw_meli_alq_temp         posicion_pagina     int64  Pendiente de documentar segun significado en l...                                                  1
97  df_raw_meli_alq_temp                    slug       str  Pendiente de documentar segun significado en l...  MLA-2698335478-departamento-alquiler-temporari...
98  df_raw_meli_alq_temp                   calle       str                         Calle extraida o inferida.                                     Av. Cnel. Díaz
99  df_raw_meli_alq_temp                  altura   float64                     Altura aproximada o declarada.                                             2400.0

## Columnas, tipos y ejemplos por dataset

In [6]:
for name, df in raw_dfs.items():
    print('\n' + '=' * 100)
    print(name, df.shape)
    display(pd.DataFrame({
        'columna': df.columns,
        'tipo_dato': [str(df[c].dtype) for c in df.columns],
        'ejemplo': [example_value(df[c]) for c in df.columns],
    }))

====================================================================================================
df_raw_meli_alq (11479, 61)

                   columna tipo_dato                                            ejemplo
0                  item_id       str                                      MLA2052442697
1                   fuente       str                                      Mercado Libre
2                      url       str  https://departamento.mercadolibre.com.ar/MLA-2...
3               search_url       str  https://inmuebles.mercadolibre.com.ar/departam...
4            pagina_origen     int64                                                  1
5           scraped_at_utc       str                   2026-09-03T16:45:14.494669+00:00
6                   titulo       str  Departamento En Alquiler De 4 Ambientes Con De...
7           tipo_propiedad       str                                       departamento
8           tipo_operacion       str                                           alquiler
9                   moneda       str                                                USD
10                  precio   float64                                             5000.0
11            precio_texto       str                                          US$ 5.000
12                   desde     int64                                                  0
13            inmobiliaria       str                                Khabbaz Propiedades
14               direccion       str      Segui Al 3600, Palermo Chico, Capital Federal
15                  barrio       str                                      Palermo Chico
16               localidad       str                                    Capital Federal
17               provincia       str                                    Capital Federal
18           ambientes_min   float64                                                4.0
19           ambientes_max   float64                                                4.0
20              banios_min   float64                                                3.0
21              banios_max   float64                                                3.0
22         dormitorios_min   float64                                                1.0
23         dormitorios_max   float64                                                1.0
24       superficie_min_m2   float64                                              210.0
25       superficie_max_m2   float64                                              210.0
26         tipo_superficie       str                                              total
27        imagen_principal       str  https://http2.mlstatic.com/D_NQ_NP_2X_926918-M...
28               destacado     int64                                                  1
29          emprendimiento     int64                                                  0
30                posesion   float64                                                NaN
31    unidades_disponibles   float64                                                NaN
32         atributos_texto       str                 4 ambs. | 3 baños | 210 m² totales
33           texto_tarjeta       str  PUBLICADO ESTA SEMANA Departamento en alquiler...
34          parse_warnings   float64                                                NaN
35         posicion_pagina     int64                                                  1
36                    slug       str  MLA-2052442697-departamento-en-alquiler-de-4-a...
37                   calle       str                                           Segui Al
38                  altura   float64                                             3600.0
39                  comuna   float64                                               14.0
40         precio_anterior   float64                                             1957.0
41           descuento_pct   float64                                           -33114.1
42           precio_m2_min   float64                                              23.81
43           precio_m2_max   float64                                              23.81
44  amplitud_superficie_m2   float64                                                0.0
45     es_rango_superficie   float64                                                0.0
46      es_rango_ambientes   float64                                                0.0
47            monoambiente     int64                                                  0
48            apto_credito     int64                                                  0
49                  balcon     int64                                                  0
50                 terraza     int64                                                  0
51                  pileta     int64                                                  0
52                parrilla     int64                                                  0
53      cochera_mencionada     int64                                                  1
54   amenities_mencionadas     int64                                                  1
55          estado_entrega    object                                  entrega_inmediata
56      cantidad_atributos     int64                                                  3
57         completitud_pct   float64                                              100.0
58               imagen_id       str         D_NQ_NP_2X_926918-MLA116997522333_082026-E
59        imagen_extension       str                                               webp
60         _archivo_origen       str  data\raw\mercadolibre_inmuebles_alquiler\meli_...

====================================================================================================
df_raw_meli_alq_temp (6190, 61)

                   columna tipo_dato                                            ejemplo
0                  item_id       str                                      MLA2698335478
1                   fuente       str                                      Mercado Libre
2                      url       str  https://departamento.mercadolibre.com.ar/MLA-2...
3               search_url       str  https://inmuebles.mercadolibre.com.ar/departam...
4            pagina_origen     int64                                                  1
5           scraped_at_utc       str                   2026-09-03T17:22:27.502870+00:00
6                   titulo       str  Departamento Alquiler Temporario 3 Ambientes A...
7           tipo_propiedad       str                                       departamento
8           tipo_operacion       str                                  alquiler temporal
9                   moneda       str                                                USD
10                  precio   float64                                             1400.0
11            precio_texto       str                                          US$ 1.400
12                   desde     int64                                                  0
13            inmobiliaria       str                            Alternativa Propiedades
14               direccion       str     Av. Cnel. Díaz 2400, Recoleta, Capital Federal
15                  barrio       str                                           Recoleta
16               localidad       str                                    Capital Federal
17               provincia       str                                    Capital Federal
18           ambientes_min   float64                                                3.0
19           ambientes_max   float64                                                3.0
20              banios_min   float64                                                3.0
21              banios_max   float64                                                3.0
22         dormitorios_min   float64                                                2.0
23         dormitorios_max   float64                                                2.0
24       superficie_min_m2   float64                                              120.0
25       superficie_max_m2   float64                                              120.0
26         tipo_superficie       str                                           cubierta
27        imagen_principal       str  https://http2.mlstatic.com/D_NQ_NP_2X_786192-M...
28               destacado     int64                                                  1
29          emprendimiento     int64                                                  0
30                posesion    object                                           Preventa
31    unidades_disponibles   float64                                                4.0
32         atributos_texto       str               3 ambs. | 3 baños | 120 m² cubiertos
33           texto_tarjeta       str  Departamento en alquiler temporal Departamento...
34          parse_warnings   float64                                                NaN
35         posicion_pagina     int64                                                  1
36                    slug       str  MLA-2698335478-departamento-alquiler-temporari...
37                   calle       str                                     Av. Cnel. Díaz
38                  altura   float64                                             2400.0
39                  comuna   float64                                                2.0
40         precio_anterior   float64                                             1500.0
41           descuento_pct   float64                                          -46566.67
42           precio_m2_min   float64                                              11.67
43           precio_m2_max   float64                                              11.67
44  amplitud_superficie_m2   float64                                                0.0
45     es_rango_superficie   float64                                                0.0
46      es_rango_ambientes   float64                                                0.0
47            monoambiente     int64                                                  0
48            apto_credito     int64                                                  0
49                  balcon     int64                                                  0
50                 terraza     int64                                                  0
51                  pileta     int64                                                  0
52                parrilla     int64                                                  0
53      cochera_mencionada     int64                                                  0
54   amenities_mencionadas     int64                                                  0
55          estado_entrega    object                                  entrega_inmediata
56      cantidad_atributos     int64                                                  3
57         completitud_pct   float64                                               85.7
58               imagen_id       str         D_NQ_NP_2X_786192-MLA102668267049_122025-E
59        imagen_extension       str                                               webp
60         _archivo_origen       str  data\raw\mercadolibre_inmuebles_alquiler tempo...

====================================================================================================
df_raw_meli_vtas (44013, 61)

                   columna tipo_dato                                            ejemplo
0                  item_id       str                                      MLA1844045092
1                   fuente       str                                      Mercado Libre
2                      url       str  https://departamento.mercadolibre.com.ar/MLA-1...
3               search_url       str  https://inmuebles.mercadolibre.com.ar/departam...
4            pagina_origen     int64                                                  1
5           scraped_at_utc       str                   2026-09-03T16:28:55.814717+00:00
6                   titulo       str                    Mine Migueletes - Bajo Belgrano
7           tipo_propiedad       str                                       departamento
8           tipo_operacion       str                                              venta
9                   moneda       str                                                USD
10                  precio   float64                                           198000.0
11            precio_texto       str                                        US$ 198.000
12                   desde     int64                                                  1
13            inmobiliaria       str                                       Martin Pinus
14               direccion       str   Migueletes 2306, Belgrano Chico, Capital Federal
15                  barrio       str                                     Belgrano Chico
16               localidad       str                                    Capital Federal
17               provincia       str                                    Capital Federal
18           ambientes_min   float64                                                2.0
19           ambientes_max   float64                                                2.0
20              banios_min   float64                                                1.0
21              banios_max   float64                                                1.0
22         dormitorios_min   float64                                                2.0
23         dormitorios_max   float64                                                2.0
24       superficie_min_m2   float64                                               38.0
25       superficie_max_m2   float64                                               44.0
26         tipo_superficie       str                                           cubierta
27        imagen_principal       str  https://http2.mlstatic.com/D_NQ_NP_2X_846087-M...
28               destacado     int64                                                  1
29          emprendimiento     int64                                                  1
30                posesion       str                                  Entrega inmediata
31    unidades_disponibles   float64                                                7.0
32         atributos_texto       str            2 ambs. | 1 baño | 38 - 44 m² cubiertos
33           texto_tarjeta       str  EMPRENDIMIENTO Departamento en venta Mine Migu...
34          parse_warnings   float64                                                NaN
35         posicion_pagina     int64                                                  1
36                    slug       str   MLA-1844045092-mine-migueletes-bajo-belgrano-_JM
37                   calle       str                                         Migueletes
38                  altura   float64                                             2306.0
39                  comuna   float64                                               13.0
40         precio_anterior   float64                                             1300.0
41           descuento_pct   float64                                           -9130.77
42           precio_m2_min   float64                                             4500.0
43           precio_m2_max   float64                                            5210.53
44  amplitud_superficie_m2   float64                                                6.0
45     es_rango_superficie   float64                                                1.0
46      es_rango_ambientes   float64                                                0.0
47            monoambiente     int64                                                  0
48            apto_credito     int64                                                  0
49                  balcon     int64                                                  0
50                 terraza     int64                                                  0
51                  pileta     int64                                                  0
52                parrilla     int64                                                  0
53      cochera_mencionada     int64                                                  0
54   amenities_mencionadas     int64                                                  0
55          estado_entrega       str                                  entrega_inmediata
56      cantidad_atributos     int64                                                  3
57         completitud_pct   float64                                               85.7
58               imagen_id       str         D_NQ_NP_2X_846087-MLA112858604644_072026-E
59        imagen_extension       str                                               webp
60         _archivo_origen       str  data\raw\mercadolibre_inmuebles_ventas\meli_vt...

====================================================================================================
df_raw_argenprop (162, 96)

                       columna tipo_dato                                            ejemplo
0                  property_id       str                               e197e9f1c643db6d77d3
1                       fuente       str                                          Argenprop
2                          url       str  https://www.argenprop.com/departamento-en-vent...
3               scraped_at_utc       str                   2026-08-15T23:56:14.395650+00:00
4                   search_url       str  https://www.argenprop.com/departamentos/venta/...
5                pagina_origen     int64                                                  1
6                  http_status     int64                                                200
7                     parse_ok     int64                                                  1
8               parse_warnings       str                   modo_listado_sin_ficha_detallada
9                       titulo       str  TORRE BELLINI! Piso alto de revista! Balcón co...
10                 descripcion   float64                                                NaN
11              tipo_operacion       str                                              venta
12              tipo_propiedad       str                                       departamento
13          estado_publicacion   float64                                                NaN
14           fecha_publicacion   float64                                                NaN
15                inmobiliaria   float64                                                NaN
16                   seller_id   float64                                                NaN
17                      moneda       str                                                USD
18                      precio   float64                                          2400000.0
19                precio_texto       str                USD 2.400.000 + $2.200.000 expensas
20             expensas_moneda       str                                                ARS
21                    expensas   float64                                           124000.0
22              expensas_texto       str                                  expensas $124.000
23         precio_m2_calculado   float64                                             8000.0
24          direccion_completa       str                             Jerónimo Salguero 2700
25                       calle       str                                  Jerónimo Salguero
26                      altura   float64                                             2700.0
27                        piso       str                                                  1
28                      unidad   float64                                                NaN
29                      barrio   float64                                                NaN
30                   localidad   float64                                                NaN
31                     partido   float64                                                NaN
32                   provincia   float64                                                NaN
33                        pais   float64                                                NaN
34               codigo_postal   float64                                                NaN
35                     latitud   float64                                                NaN
36                    longitud   float64                                                NaN
37                   ambientes   float64                                                2.0
38                 dormitorios   float64                                                3.0
39                      banios   float64                                                1.0
40                   toilettes   float64                                                NaN
41                    cocheras   float64                                                2.0
42         superficie_total_m2   float64                                              300.0
43      superficie_cubierta_m2   float64                                               91.0
44   superficie_descubierta_m2   float64                                                NaN
45  superficie_semicubierta_m2   float64                                                NaN
46       superficie_terreno_m2   float64                                                NaN
47                    frente_m   float64                                                NaN
48                     fondo_m   float64                                                NaN
49            antiguedad_anios   float64                                                NaN
50             estado_inmueble   float64                                                NaN
51                 disposicion   float64                                                NaN
52                 orientacion   float64                                                NaN
53                 luminosidad   float64                                                NaN
54            cantidad_plantas   float64                                                NaN
55     cantidad_pisos_edificio   float64                                                NaN
56      departamentos_por_piso   float64                                                NaN
57                apto_credito   float64                                                NaN
58            apto_profesional   float64                                                NaN
59            permite_mascotas   float64                                                NaN
60               accesibilidad   float64                                                NaN
61                    amoblado   float64                                                NaN
62                      balcon   float64                                                NaN
63                     terraza   float64                                                NaN
64                       patio   float64                                                NaN
65                      jardin   float64                                                NaN
66                    parrilla   float64                                                NaN
67                      pileta   float64                                                NaN
68                         sum   float64                                                NaN
69                    gimnasio   float64                                                NaN
70                       sauna   float64                                                NaN
71                     laundry   float64                                                NaN
72                     baulera   float64                                                NaN
73                    ascensor   float64                                                NaN
74               seguridad_24h   float64                                                NaN
75                  vigilancia   float64                                                NaN
76          aire_acondicionado   float64                                                NaN
77                 calefaccion   float64                                                NaN
78               losa_radiante   float64                                                NaN
79                 gas_natural   float64                                                NaN
80              agua_corriente   float64                                                NaN
81                electricidad   float64                                                NaN
82                      cloaca   float64                                                NaN
83                    internet   float64                                                NaN
84                   vista_rio   float64                                                NaN
85               vista_abierta   float64                                                NaN
86                   reciclado   float64                                                NaN
87               a_refaccionar   float64                                                NaN
88           cantidad_imagenes     int64                                                  9
89            imagen_principal       str  https://www.argenprop.com/static-content/32499...
90                   video_url   float64                                                NaN
91            tour_virtual_url   float64                                                NaN
92    cantidad_atributos_extra     int64                                                  1
93        atributos_extra_json       str  {"texto_tarjeta": "+ 38 Ver más fotos 1 /46 Vi...
94                  jsonld_raw   float64                                                NaN
95             _archivo_origen       str       data\raw\argenprop\propiedades_argenprop.csv

====================================================================================================
df_raw_zonaprop (980, 96)

                       columna tipo_dato                                            ejemplo
0                  property_id       str                               174f7e930591b69560cf
1                       fuente       str                                           Zonaprop
2                          url       str  https://www.zonaprop.com.ar/propiedades/clasif...
3               scraped_at_utc       str                   2026-08-17T20:48:48.072806+00:00
4                   search_url       str  https://www.zonaprop.com.ar/departamentos-vent...
5                pagina_origen     int64                                                  1
6                  http_status     int64                                                200
7                     parse_ok     int64                                                  1
8               parse_warnings       str                   modo_listado_sin_ficha_detallada
9                       titulo       str  Una nueva forma de vivir el sur porteño. Desar...
10                 descripcion   float64                                                NaN
11              tipo_operacion       str                                              venta
12              tipo_propiedad   float64                                                NaN
13          estado_publicacion   float64                                                NaN
14           fecha_publicacion   float64                                                NaN
15                inmobiliaria       str                                        USD 120.000
16                   seller_id   float64                                                NaN
17                      moneda       str                                                USD
18                      precio   float64                                           120000.0
19                precio_texto       str                                        USD 120.000
20             expensas_moneda       str                                                ARS
21                    expensas   float64                                              119.0
22              expensas_texto       str                                       Expensas 119
23         precio_m2_calculado   float64                                            2142.86
24          direccion_completa       str                      Villa Lugano, Capital Federal
25                       calle       str                                       Villa Lugano
26                      altura   float64                                                NaN
27                        piso       str                                              uerto
28                      unidad   float64                                                NaN
29                      barrio   float64                                                NaN
30                   localidad   float64                                                NaN
31                     partido   float64                                                NaN
32                   provincia   float64                                                NaN
33                        pais   float64                                                NaN
34               codigo_postal   float64                                                NaN
35                     latitud   float64                                                NaN
36                    longitud   float64                                                NaN
37                   ambientes   float64                                                2.0
38                 dormitorios   float64                                                1.0
39                      banios   float64                                                1.0
40                   toilettes   float64                                                NaN
41                    cocheras   float64                                                2.0
42         superficie_total_m2   float64                                               56.0
43      superficie_cubierta_m2   float64                                               85.0
44   superficie_descubierta_m2   float64                                                NaN
45  superficie_semicubierta_m2   float64                                                NaN
46       superficie_terreno_m2   float64                                                NaN
47                    frente_m   float64                                                NaN
48                     fondo_m   float64                                                NaN
49            antiguedad_anios   float64                                                NaN
50             estado_inmueble   float64                                                NaN
51                 disposicion   float64                                                NaN
52                 orientacion   float64                                                NaN
53                 luminosidad   float64                                                NaN
54            cantidad_plantas   float64                                                NaN
55     cantidad_pisos_edificio   float64                                                NaN
56      departamentos_por_piso   float64                                                NaN
57                apto_credito   float64                                                NaN
58            apto_profesional   float64                                                NaN
59            permite_mascotas   float64                                                NaN
60               accesibilidad   float64                                                NaN
61                    amoblado   float64                                                NaN
62                      balcon   float64                                                NaN
63                     terraza   float64                                                NaN
64                       patio   float64                                                NaN
65                      jardin   float64                                                NaN
66                    parrilla   float64                                                NaN
67                      pileta   float64                                                NaN
68                         sum   float64                                                NaN
69                    gimnasio   float64                                                NaN
70                       sauna   float64                                                NaN
71                     laundry   float64                                                NaN
72                     baulera   float64                                                NaN
73                    ascensor   float64                                                NaN
74               seguridad_24h   float64                                                NaN
75                  vigilancia   float64                                                NaN
76          aire_acondicionado   float64                                                NaN
77                 calefaccion   float64                                                NaN
78               losa_radiante   float64                                                NaN
79                 gas_natural   float64                                                NaN
80              agua_corriente   float64                                                NaN
81                electricidad   float64                                                NaN
82                      cloaca   float64                                                NaN
83                    internet   float64                                                NaN
84                   vista_rio   float64                                                NaN
85               vista_abierta   float64                                                NaN
86                   reciclado   float64                                                NaN
87               a_refaccionar   float64                                                NaN
88           cantidad_imagenes     int64                                                  2
89            imagen_principal       str  https://imgar.zonapropcdn.com/avisos/1/00/59/5...
90                   video_url   float64                                                NaN
91            tour_virtual_url   float64                                                NaN
92    cantidad_atributos_extra     int64                                                  1
93        atributos_extra_json       str  {"texto_tarjeta": "USD 120.000 56 m² tot. 2 am...
94                  jsonld_raw   float64                                                NaN
95             _archivo_origen       str         data\raw\zonaprop\propiedades_zonaprop.csv

====================================================================================================
df_raw_airbnb_norm (9596, 61)

                  columna tipo_dato                                            ejemplo
0             property_id     int64                                1040554442322631694
1                  fuente       str                                             Airbnb
2          tipo_operacion       str                                  alquiler temporal
3           unidad_precio       str                     por_noche_2_huespedes_5_noches
4                     url       str  https://www.airbnb.com.ar/rooms/10405544423226...
5          scraped_at_utc       str                               2026-09-05T17:38:48Z
6                  titulo       str           La mejor ubicación en Palermo - La Rural
7             descripcion       str  Cómodo y céntrico departamento en el corazón d...
8          tipo_propiedad       str        Departamento con servicios incluidos entero
9               room_type       str                                    Entire home/apt
10  categoria_alojamiento       str                                    vivienda_entera
11            es_vivienda      bool                                               True
12   acepta_corta_estadia      bool                                               True
13     solo_larga_estadia      bool                                              False
14         precio_regimen       str                                            mensual
15                 moneda       str                                                USD
16                 precio   float64                                               30.0
17           precio_texto       str                                          $ 900 USD
18      precio_sospechoso      bool                                              False
19                 barrio       str                                            Palermo
20            barrio_norm       str                                            palermo
21                 comuna   float64                                               14.0
22                latitud   float64                                           -34.5794
23               longitud   float64                                           -58.4236
24              ambientes   float64                                                2.0
25            dormitorios   float64                                                1.0
26                 banios   float64                                                1.0
27              toilettes   float64                                                0.0
28                  camas   float64                                                2.0
29              capacidad     int64                                                  2
30              seller_id     int64                                          549766754
31          seller_nombre       str                                               Rosi
32       seller_superhost      bool                                              False
33                 rating   float64                                                4.8
34                reviews   float64                                                5.0
35      cantidad_imagenes     int64                                                 16
36       imagen_principal       str  https://a0.muscache.com/im/pictures/hosting/Ho...
37               ascensor      bool                                               True
38         balcon_o_patio      bool                                              False
39                terraza      bool                                              False
40                 jardin      bool                                              False
41               parrilla      bool                                              False
42                 pileta      bool                                              False
43               gimnasio      bool                                              False
44                  sauna      bool                                              False
45                laundry      bool                                              False
46                cochera      bool                                              False
47      camaras_seguridad      bool                                              False
48                portero      bool                                              False
49     aire_acondicionado      bool                                              False
50            calefaccion      bool                                               True
51          losa_radiante      bool                                              False
52               internet      bool                                               True
53                  vista      bool                                              False
54           zona_trabajo      bool                                               True
55       permite_mascotas      bool                                              False
56               amoblado      bool                                               True
57              localidad       str                    Ciudad Autónoma de Buenos Aires
58              provincia       str                                               CABA
59                   pais       str                                          Argentina
60        _archivo_origen       str  data\raw\airbnb\airbnb_caba_normalizado_mensua...

## Perfil de calidad por columna

In [7]:
perfil_calidad_raw = pd.concat([quality_profile(df, name) for name, df in raw_dfs.items()], ignore_index=True)
perfil_calidad_raw = perfil_calidad_raw.sort_values(['dataset', 'pct_nulos_iniciales', 'pct_invalidos_tipo_faltante'], ascending=[True, False, False])
display(perfil_calidad_raw.head(160))
perfil_calidad_raw.to_csv(PROCESSED_DIR / 'perfil_calidad_raw.csv', index=False)
#analisis rapido de la calidad

,dataset,columna,tipo_dato,tipo_variable,n_filas,nulos_iniciales,pct_nulos_iniciales,invalidos_tipo_faltante,pct_invalidos_tipo_faltante,min_cuantitativa,max_cuantitativa,n_labels_categorica,comentario_usabilidad_calidad
408,df_raw_airbnb_norm,rating,float64,cuantitativa,9596,1522,15.86,0,0.0,1.0,5.0,NaN,media: usable con controles y posible segmenta...
409,df_raw_airbnb_norm,reviews,float64,cuantitativa,9596,1522,15.86,0,0.0,1.0,1140.0,NaN,media: usable con controles y posible segmenta...
403,df_raw_airbnb_norm,camas,float64,cuantitativa,9596,189,1.97,0,0.0,1.0,40.0,NaN,alta: utilizable para analisis inicial
394,df_raw_airbnb_norm,barrio,str,categorica/texto/fecha,9596,77,0.80,0,0.0,NaN,NaN,45.0,alta: utilizable para analisis inicial
395,df_raw_airbnb_norm,barrio_norm,str,categorica/texto/fecha,9596,77,0.80,0,0.0,NaN,NaN,45.0,alta: utilizable para analisis inicial
...,...,...,...,...,...,...,...,...,...,...,...,...,...
276,df_raw_argenprop,atributos_extra_json,str,categorica/texto/fecha,162,0,0.00,0,0.0,NaN,NaN,162.0,alta: utilizable para analisis inicial
278,df_raw_argenprop,_archivo_origen,str,categorica/texto/fecha,162,0,0.00,0,0.0,NaN,NaN,1.0,alta: utilizable para analisis inicial
30,df_raw_meli_alq,posesion,float64,cuantitativa,11479,11479,100.00,0,0.0,NaN,NaN,NaN,baja: faltantes muy altos; usar solo como refe...
31,df_raw_meli_alq,unidades_disponibles,float64,cuantitativa,11479,11479,100.00,0,0.0,NaN,NaN,NaN,baja: faltantes muy altos; usar solo como refe...
34,df_raw_meli_alq,parse_warnings,float64,cuantitativa,11479,11479,100.00,0,0.0,NaN,NaN,NaN,baja: faltantes muy altos; usar solo como refe...

## Variables con mayores problemas de completitud

In [8]:
problemas_completitud = (
    perfil_calidad_raw
    .query('pct_nulos_iniciales >= 20 or pct_invalidos_tipo_faltante >= 5')
    .sort_values(['dataset', 'pct_nulos_iniciales', 'pct_invalidos_tipo_faltante'], ascending=[True, False, False])
)
display(problemas_completitud)
problemas_completitud.to_csv(REPORTS_DIR / 'problemas_completitud_raw.csv', index=False)

,dataset,columna,tipo_dato,tipo_variable,n_filas,nulos_iniciales,pct_nulos_iniciales,invalidos_tipo_faltante,pct_invalidos_tipo_faltante,min_cuantitativa,max_cuantitativa,n_labels_categorica,comentario_usabilidad_calidad
193,df_raw_argenprop,descripcion,float64,cuantitativa,162,162,100.00,0,0.0,NaN,NaN,NaN,baja: faltantes muy altos; usar solo como refe...
196,df_raw_argenprop,estado_publicacion,float64,cuantitativa,162,162,100.00,0,0.0,NaN,NaN,NaN,baja: faltantes muy altos; usar solo como refe...
197,df_raw_argenprop,fecha_publicacion,float64,cuantitativa,162,162,100.00,0,0.0,NaN,NaN,NaN,baja: faltantes muy altos; usar solo como refe...
198,df_raw_argenprop,inmobiliaria,float64,cuantitativa,162,162,100.00,0,0.0,NaN,NaN,NaN,baja: faltantes muy altos; usar solo como refe...
199,df_raw_argenprop,seller_id,float64,cuantitativa,162,162,100.00,0,0.0,NaN,NaN,NaN,baja: faltantes muy altos; usar solo como refe...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,df_raw_zonaprop,cocheras,float64,cuantitativa,980,916,93.47,0,0.0,1.0,200.0,NaN,baja: faltantes muy altos; usar solo como refe...
306,df_raw_zonaprop,piso,str,categorica/texto/fecha,980,613,62.55,0,0.0,NaN,NaN,5.0,media-baja: requiere justificacion antes de us...
300,df_raw_zonaprop,expensas,float64,cuantitativa,980,326,33.27,0,0.0,3.0,672.0,NaN,media: usable con controles y posible segmenta...
301,df_raw_zonaprop,expensas_texto,str,categorica/texto/fecha,980,326,33.27,0,0.0,NaN,NaN,182.0,media: usable con controles y posible segmenta...
317,df_raw_zonaprop,dormitorios,float64,cuantitativa,980,214,21.84,0,0.0,1.0,21.0,NaN,media: usable con controles y posible segmenta...

En principio las columnas con 100% no aportan usabilidad, aunque no se descarta completarlas con fuentes externas, ingenieria de atributos, etc. Si la columna entera esta vacia, lo mas probable se deba a problemas en la carga y el scrapping; pendiente de analisis en los futuros notebooks y la entrega 3 donde se trabaje con texto.

## Rangos de variables cuantitativas

Este control va a permitir detectar valores extremos, errores de escala y columnas numéricas que en realidad son flags o identificadores. El tratamiento de outliers queda separado en el notebook 04.

In [9]:
rangos = []
for name, df in raw_dfs.items():
    num_cols = df.select_dtypes(include='number').columns
    if len(num_cols) == 0:
        continue
    tmp = df[num_cols].describe(percentiles=[0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99]).T.reset_index()
    tmp = tmp.rename(columns={'index': 'columna'})
    tmp.insert(0, 'dataset', name)
    rangos.append(tmp)

rangos_cuantitativos_raw = pd.concat(rangos, ignore_index=True) if rangos else pd.DataFrame()
display(rangos_cuantitativos_raw)
rangos_cuantitativos_raw.to_csv(REPORTS_DIR / 'rangos_cuantitativos_raw.csv', index=False)

,dataset,columna,count,mean,std,min,1%,5%,25%,50%,75%,95%,99%,max
0,df_raw_meli_alq,pagina_origen,11479.0,8.589337e+00,9.126467e+00,1.0,1.0,1.0,2.00,5.000000e+00,1.200000e+01,3.100000e+01,4.000000e+01,4.200000e+01
1,df_raw_meli_alq,precio,11479.0,6.479774e+05,1.161667e+06,10.0,500.0,750.0,4000.00,6.500000e+05,8.800000e+05,1.500000e+06,2.300000e+06,1.111111e+08
2,df_raw_meli_alq,desde,11479.0,6.969248e-04,2.639128e-02,0.0,0.0,0.0,0.00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
3,df_raw_meli_alq,ambientes_min,11140.0,2.187882e+00,1.313836e+00,1.0,1.0,1.0,1.00,2.000000e+00,3.000000e+00,4.000000e+00,5.000000e+00,7.100000e+01
4,df_raw_meli_alq,ambientes_max,11140.0,2.187882e+00,1.313836e+00,1.0,1.0,1.0,1.00,2.000000e+00,3.000000e+00,4.000000e+00,5.000000e+00,7.100000e+01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,df_raw_airbnb_norm,capacidad,9596.0,2.945185e+00,1.458231e+00,2.0,2.0,2.0,2.00,2.000000e+00,4.000000e+00,5.000000e+00,8.000000e+00,2.600000e+01
271,df_raw_airbnb_norm,seller_id,9596.0,3.068990e+16,2.272244e+17,13426.0,416887.1,2120738.0,36668835.00,1.604368e+08,4.692825e+08,6.971964e+08,1.706666e+18,1.767139e+18
272,df_raw_airbnb_norm,rating,8074.0,4.736255e+00,4.271341e-01,1.0,3.0,4.0,4.68,4.840000e+00,4.970000e+00,5.000000e+00,5.000000e+00,5.000000e+00
273,df_raw_airbnb_norm,reviews,8074.0,3.814144e+01,5.276317e+01,1.0,1.0,1.0,6.00,1.900000e+01,5.100000e+01,1.323500e+02,2.380000e+02,1.140000e+03
274,df_raw_airbnb_norm,cantidad_imagenes,9596.0,2.680638e+01,1.902583e+01,1.0,5.0,8.0,15.00,2.300000e+01,3.300000e+01,5.800000e+01,9.000000e+01,4.500000e+02

## Cardinalidad de variables categóricas

In [10]:
cardinalidades = []
for name, df in raw_dfs.items():
    cat_cols = df.select_dtypes(include=['object', 'string', 'category', 'bool']).columns
    for col in cat_cols:
        vc = df[col].astype('string').str.strip().value_counts(dropna=False).head(10)
        cardinalidades.append({
            'dataset': name,
            'columna': col,
            'n_labels_incluyendo_na': int(df[col].nunique(dropna=False)),
            'top_10_labels': ' | '.join([f'{idx}: {val}' for idx, val in vc.items()])[:1000],
        })
cardinalidad_categoricas_raw = pd.DataFrame(cardinalidades).sort_values(['dataset', 'n_labels_incluyendo_na'], ascending=[True, False])
display(cardinalidad_categoricas_raw.head(140))
cardinalidad_categoricas_raw.to_csv(REPORTS_DIR / 'cardinalidad_categoricas_raw.csv', index=False)

                dataset           columna  n_labels_incluyendo_na                                      top_10_labels
118  df_raw_airbnb_norm               url                    9596  https://www.airbnb.com.ar/rooms/10405544423226...
119  df_raw_airbnb_norm    scraped_at_utc                    9596  2026-09-05T17:38:48Z: 1 | 2026-09-06T01:02:39Z...
136  df_raw_airbnb_norm  imagen_principal                    9399  https://a0.muscache.com/im/pictures/b3dd86a1-e...
120  df_raw_airbnb_norm            titulo                    9201  Departamento en Buenos Aires: 25 | Departament...
121  df_raw_airbnb_norm       descripcion                    8801  Disfrutá de la sencillez de este alojamiento t...
..                  ...               ...                     ...                                                ...
59     df_raw_meli_vtas            moneda                       2                                USD: 44010 | ARS: 3
65     df_raw_meli_vtas         provincia                       2                   Capital Federal: 44009 | <NA>: 4
75     df_raw_meli_vtas  imagen_extension                       2                               webp: 44012 | jpg: 1
76     df_raw_meli_vtas   _archivo_origen                       2  data\raw\mercadolibre_inmuebles_ventas\meli_vt...
52     df_raw_meli_vtas            fuente                       1                               Mercado Libre: 44013

[140 rows x 4 columns]

Revisar este reporte permite revisar rapidamente si las labels efectivamente corresponden a categorizaciones pertinentes o si abundan columnas categoricas de alta cardianlidad (fechas, ids, etc). Su tratamiento se decide en ingenieria de variables (buckets).

## Duplicados iniciales

In [11]:
keys_candidates = ['item_id', 'property_id', 'url']
rows = []
for name, df in raw_dfs.items():
    row = {'dataset': name, 'filas': len(df), 'duplicados_exactos': int(df.duplicated().sum())}
    for key in keys_candidates:
        if key in df.columns:
            row[f'duplicados_por_{key}'] = int(df.duplicated(subset=[key]).sum())
            row[f'n_unicos_{key}'] = int(df[key].nunique(dropna=True))
    rows.append(row)
duplicados_raw = pd.DataFrame(rows)
display(duplicados_raw)
duplicados_raw.to_csv(REPORTS_DIR / 'duplicados_raw.csv', index=False)

                dataset  filas  duplicados_exactos  duplicados_por_item_id  n_unicos_item_id  duplicados_por_url  n_unicos_url  duplicados_por_property_id  n_unicos_property_id
0       df_raw_meli_alq  11479                   0                  1602.0            9877.0                1583          9896                         NaN                   NaN
1  df_raw_meli_alq_temp   6190                   0                  1696.0            4494.0                1690          4500                         NaN                   NaN
2      df_raw_meli_vtas  44013                   0                  1235.0           42778.0                1188         42825                         NaN                   NaN
3      df_raw_argenprop    162                   0                     NaN               NaN                   0           162                         0.0                 162.0
4       df_raw_zonaprop    980                   0                     NaN               NaN                   0           980                         0.0                 980.0
5    df_raw_airbnb_norm   9596                   0                     NaN               NaN                   0          9596                         0.0                9596.0

Existen 0 duplicados exactos, aunque parece repetirse propiedades. Se debera corroboraar que efectivamente se tratan de la misma propiedad y unificar los datos, aunque dos publicaciones diferentes pueden incluir diferentes precios. Se decidira un tratamiento adecuado de acuerdo a los alcances del analisis.

## Cierre del perfilado raw

Hallazgos a trasladar al notebook 02:

- Las fuentes deben normalizarse por separado antes de consolidar, porque tienen estructuras y campos propios. Se mantienen DFs separados por estas etapas para evitar mezclar estructuras, generar nulos artificialmente, etc.
- Los faltantes estructurales entre portales no deben confundirse con problemas de calidad. Se deben analizar los faltantes segun su proporcion en cada columna y aleatoriedad/ falta de. 
- Las variables de precio, superficie, moneda, barrio/comuna y operación son críticas para el análisis posterior.
- Los valores extremos se identifican preliminarmente en esta etapa, pero se tratan con flags específicos en el notebook 04, definiendo analisis y decision.